---

- name: Copying file
  hosts: [RHEL]
  become: yes
  tasks:

    - name: Copying a existing file from control node to managed node
      copy:

        src: /home/varunanand/my-playbooks-practise/copy-module/inventory.ini
        dest: /home/varunanand/
